Automated merge with file:///proj/maxwell/hg/maxine

diff --git a/bin/max b/bin/max
--- a/bin/max
+++ b/bin/max
@@ -417,35 +417,30 @@ function run_build() {
                 exit $result
             fi
         done
-
-        if [ "$project_dir" = "VM" ]; then
-            # Regenerate javatester files
-            pushd $maxine_dir/VM/test >/dev/null
-            jtt_tests="jtt/bytecode"
-            jtt_tests="$jtt_tests jtt/except"
-            jtt_tests="$jtt_tests jtt/optimize"
-            jtt_tests="$jtt_tests jtt/directives"
-            jtt_tests="$jtt_tests jtt/lang"
-            jtt_tests="$jtt_tests jtt/hotpath"
-            jtt_tests="$jtt_tests jtt/reflect"
-            jtt_tests="$jtt_tests jtt/jdk"
-            jtt_tests="$jtt_tests jtt/threads"
-            jtt_tests="$jtt_tests jtt/micro"
-            jtt_tests="$jtt_tests jtt/jvmni"
-            jtt_tests="$jtt_tests jtt/jni"
-            run ${jvm_exe} -cp $(get_project_cp Base):$(get_project_cp VM) test.com.sun.max.vm.compiler.JavaTester -scenario=target -run-scheme-package=all -native-tests $jtt_tests > /dev/null 
-            result=$?
-            popd >/dev/null
-            if [ $result -ne 0 ]; then
-                echo "JavaTester found that JavaTesterRunScheme.java or JavaTesterTests.java"
-                echo "needed updating (and did so)."
-                echo "To push your changes to the repository, these files need to be"
-                echo "generated locally and checked in."
-                echo "(The files can be generated by running: max build VM)"
-                exit $result
-            fi
-        fi
     done
+}
+
+#=======================================
+# 'jttgen' command
+#=======================================
+
+jttgen_help="(re)generate harness and run scheme for the JavaTester tests
+
+    Run the JavaTester to update the JavaTesterRunScheme.java and JavaTesterTests.java
+    files in the com.sun.max.vm.jtrun.all package."
+
+function run_jttgen() {
+    if [ $# -ne 0 ]; then
+        run_help jttgen
+        exit 1
+    fi
+    
+    pushd $maxine_dir/VM/test >/dev/null
+    run ${jvm_exe} -cp $(get_project_cp Base):$(get_project_cp VM) test.com.sun.max.vm.compiler.JavaTester \
+        -scenario=target -run-scheme-package=all -native-tests $(echo jtt/* | sed 's:jtt/fail::g')  
+    result=$?
+    popd >/dev/null
+    exit $result
 }
 
 #=======================================
@@ -472,8 +467,8 @@ function run_check() {
                 CHECKSTYLE_JAR=$1
                 ;;
             -* )
-                echo "unknown build option '$1'"
                 run_help check
+                echo "unknown build option '$1'"
                 exit 1
                 ;;
             * )
@@ -906,7 +901,13 @@ function run_inspect() {
 # 'jtest' command
 #=======================================
 
-jtest_help="run the Java Tester"
+jtest_usage="[VM options] -- [Java Tester options]"
+jtest_help="run the Java Tester
+    
+    Use \"max jtest -- -help\" to see what the JavaTester options are. These options
+    must be separated from the VM options with '--'.
+    
+    Use \"max jtest -help\" to see what the VM options are."
 
 function run_jtest() {
     vm_args=""
