Fixed bug in reference map interpreter when encountering methods with unreachable bytecode. Some of the bytecode generated by jython contains unreachable code.
Added -XX:SaveClassDir=<dir> VM option to support saving all class files loaded and/or generated by the VM to the file system.
This simplifies the task of making such classes visible to the Inspector and the 'max inspect' command has been modified to make
use of this.

diff --git a/bin/max b/bin/max
--- a/bin/max
+++ b/bin/max
@@ -1041,9 +1041,12 @@ inspect_help="launch a given program under the Inspector
 
 function run_inspect() {
 
-    vm_args=""
+    save_class_dir="$MAXVM_DIR/inspected_classes"
+    vm_args="-XX:SaveClassDir=$save_class_dir"
     inspector_args="-vmdir=$MAXVM_DIR"
-    inspector_cp="";
+    inspector_cp="$MAXVM_DIR/inspected_classes"
+    mkdir -p $save_class_dir || { echo "Failed to created directory $save_class_dir"; exit 1; }
+    
     while [ "$1" != "" ]; do
         case $1 in
             -XX:LogFile=*)
@@ -1071,6 +1074,12 @@ function run_inspect() {
             --* )
                 inspector_args="$inspector_args ${1/-/}"
                 ;;
+            -XX:SaveClassDir=*)
+                vm_args="$vm_args $1"
+                save_class_dir=${1/*=/}
+                mkdir -p $save_class_dir || { echo "Failed to created directory $save_class_dir"; exit 1; }
+                inspector_cp="$inspector_cp:$save_class_dir"
+                ;;
             *)
                 vm_args="$vm_args $1"
                 ;;
@@ -1079,7 +1088,7 @@ function run_inspect() {
     done    
 
 	if [ -n "$inspector_cp" ]; then
-	    inspector_args="$inspector_args -cp=${inspector_cp/:/}"
+	    inspector_args="$inspector_args -cp=${inspector_cp/#:/}"
 	fi
 
     if [ "$MAXINE_OS" = "darwin" ]; then
