Automated merge with file:///proj/maxwell/hg/maxine

diff --git a/bin/max b/bin/max
--- a/bin/max
+++ b/bin/max
@@ -292,9 +292,14 @@ build_help="compile the Maxine Java and C sources, linking the latter
    Compile all or some of the Maxine source code using the appropriate compilers
    and linkers for the various source code types.
    
+   If the CHECKSTYLE_JAR environment variable denotes the path to a Checkstyle
+   jar file, then Checkstyle is also run over the sources. Any errors or warnings
+   produced by Checkstyle cause the build to fail.
+   
 options:
  -clean     removes existing binaries and class files before building projects
  -javac     path to a Java source compiler (default: ${JAVA_HOME}/bin/javac)
+ -cs        run Checkstyle over source if path to a Checkstyle 4 jar (default: value of CHECKSTYLE4_CP environment variable
 
 If no projects are given, then all projects are built."
 
@@ -384,13 +389,54 @@ function run_build() {
                                               { if (c-- >= 0) next; print; }
                      END                      { if (s > 0) print "Suppressed " s " warnings about use of Sun implementation classes" }'
             
-            result=$?
+            result=${PIPESTATUS[0]}
+            if [ $result -eq 0 ]; then
+                # Copying non Java source files from 'src' to 'bin'
+                for file in `find . -type f | grep -v '.java$'`; do
+                    if [ -d ../bin/$(dirname $file) ]; then
+                       run cp $file ../bin/$file
+                    fi
+                done
+                
+                # Run Checkstyle
+                if [ -n "$CHECKSTYLE_JAR" -a -f $maxine_dir/$project_dir/.checkstyle ]; then
+                    checks_file=$(grep 'location=' < $maxine_dir/$project_dir/.checkstyle | sed 's:.*location="\([^"]*\)".*:\1:g')
+                    if [[ "$checks_file" = /* ]]; then
+                        checks_file=${checks_file/#\//$maxine_dir/}
+                    else
+                        checks_file="$maxine_dir/$project_dir/$checks_file"
+                    fi
+                
+                    echo "Running Checkstyle using $checks_file..."
+                    checkstyle_out=/tmp/audit.$$
+                    checkstyle_input=/tmp/checkfiles.txt.$$
+
+                    cat $javac_input | \
+                        grep -v 'test/bytecode/' |\
+                        grep -v 'test/except/' |\
+                        grep -v 'test/interactive/' |\
+                        grep -v 'test/jdk/' |\
+                        grep -v 'test/lang/' |\
+                        grep -v 'test/micro/' |\
+                        grep -v 'test/optimize/' |\
+                        grep -v 'test/reflect/' |\
+                        grep -v 'test/threads/' >$checkstyle_input
+                    
+                    run $jvm -Xmx1g -jar $CHECKSTYLE_JAR -c $checks_file $(cat $checkstyle_input) -o $checkstyle_out
+                    result=$?
+                    rm $checkstyle_input
+                    if [ $result -eq 0 ]; then
+	                    if [ "X$(grep 'warning:' <$checkstyle_out)" != "X" ]; then
+                            cat $checkstyle_out
+	                        result=1
+	                    fi
+	                else
+                        cat $checkstyle_out
+	                fi
+	                rm $checkstyle_out
+	             fi
+            fi
             rm $javac_input
-            for file in `find . -type f | grep -v '.java$'`; do
-                if [ -d ../bin/$(dirname $file) ]; then
-                   run cp $file ../bin/$file
-                fi
-            done
             popd >/dev/null
             if [ $result -ne 0 ]; then
                 exit $result
@@ -475,15 +521,81 @@ function run_javadoc() {
 # 'image' command
 #=======================================
 
+image_configs=( \
+    java:-run=java \
+    optopt:-run=test.com.sun.max.vm.testrun.all,-native-tests \
+    optjit:-run=test.com.sun.max.vm.testrun.all,-native-tests,-test-callee-jit \
+    jitopt:-run=test.com.sun.max.vm.testrun.all,-native-tests,-test-caller-jit \
+    jitjit:-run=test.com.sun.max.vm.testrun.all,-native-tests,-test-caller-jit,-test-callee-jit \
+)
+
 image_usage="[options]"
 image_help="build a boot image
 
-    Run the com.sun.max.vm.prototype.BinaryImageGenerator class to build a Maxine boot image.
+    Run the BinaryImageGenerator to build a Maxine boot image.
+    
+    An option starting with '@' denotes a preconfigured set of
+    options. The available preconfigured option sets are:  
+"
+    
+image_help=$(printf "%s\n    %-15s %s\n " "$image_help" "Configuration" "Expansion")
+for image_config in ${image_configs[@]}; do
+    image_config_args="${image_config/*:/}"
+    image_help=$(printf "%s\n    @%-15s %s" "$image_help" "${image_config/:*/}" "${image_config_args//,/ }")
+done
+
+image_help="$image_help
+    
+    An option starting with '--' is interpreted as a VM option of the same name
+    after the leading '-' is removed. Note that not all VM options have an
+    effect during image building. For example, to use the '-verbose:class' VM option
+    to trace class loading while image building, specify '--verbose:class'.
     
     Use \"max image -help\" to see what other options this command accepts."
-
+    
 function run_image() {
-    run ${jvm_exe} -cp ${maxine_cp} com.sun.max.vm.prototype.BinaryImageGenerator -trace=1 -run=java $@
+
+    vm_args=""
+    image_args=""
+    while [ "$1" != "" ]; do
+        case $1 in
+            @*)
+                image_config_arg=${1/@/}
+                image_config_found=false
+                for image_config in ${image_configs[@]}; do
+                    image_config_name=${image_config/:*/}
+                    if [ "$image_config_name" = "$image_config_arg" ]; then
+                        image_config_args="${image_config/*:/}"
+                        image_args="$image_args ${image_config_args//,/ }"
+                        image_config_found=true
+                        break
+                    fi
+                done
+                if ! $image_config_found ; then
+                    echo "Invalid image configuration: $1"
+                    run_help image
+                    exit 1
+                fi
+                ;;
+            --* )
+                if [ -z "$vm_args" ]; then
+                    vm_args="${1/-/}"
+                else
+                    vm_args="$vm_args ${1/-/}"
+                fi
+                ;;
+            *)
+                image_args="$image_args $1"
+                ;;
+        esac
+        shift
+    done    
+
+    if [ -z "$vm_args" ]; then
+        run ${jvm_exe} -cp ${maxine_cp} com.sun.max.vm.prototype.BinaryImageGenerator -trace=1 -run=java $image_args
+    else
+        run ${jvm_exe} -cp ${maxine_cp} com.sun.max.vm.prototype.BinaryImageGenerator -trace=1 -run=java $image_args -vmargs="$vm_args"
+    fi
 }
 
 #=======================================
