Fixed macro expansion for image command so that expanded arguments are subjected to complete argument processing.

diff --git a/bin/max b/bin/max
--- a/bin/max
+++ b/bin/max
@@ -752,7 +752,7 @@ function run_javadoc() {
 image_configs=( \
     java#-run=java \
     c1x-opt0#-c1x-optlevel=0,-jit=com.sun.max.vm.compiler.c1x \
-    c1x-opt0-xir#-c1x-optlevel=0,-jit=com.sun.max.vm.compiler.c1x,-XX:+GenerateLIRXIR,-XX:+GenerateUnresolvedLIRXIR \
+    c1x-opt0-xir#-c1x-optlevel=0,-jit=com.sun.max.vm.compiler.c1x,--XX:+GenerateLIRXIR,--XX:+GenerateUnresolvedLIRXIR \
     cpsc1x#-native-tests,-test-callee-c1x,-run=test.com.sun.max.vm.jtrun.all \
     cpscps#-run=test.com.sun.max.vm.jtrun.all,-native-tests \
     cpsjit#-run=test.com.sun.max.vm.jtrun.all,-native-tests,-test-callee-jit \
@@ -793,21 +793,22 @@ function run_image() {
         case $1 in
             @*)
                 image_config_arg=${1/@/}
-                image_config_found=false
                 for image_config in ${image_configs[@]}; do
                     image_config_name=${image_config/\#*/}
                     if [ "$image_config_name" = "$image_config_arg" ]; then
                         image_config_args="${image_config/*\#/}"
-                        image_args="$image_args ${image_config_args//,/ }"
-                        image_config_found=true
-                        break
+
+                        # Prepand the expanded macro to the positional parameters
+                        shift
+                        set -- ${image_config_args//,/ } "$@"
+
+                        # Continue at the outer 'while' loop                         
+                        continue 2
                     fi
                 done
-                if ! $image_config_found ; then
-                    echo "Invalid image configuration: $1"
-                    run_help image
-                    exit 1
-                fi
+                echo "Invalid image configuration: $1"
+                run_help image
+                exit 1
                 ;;
             --* )
                 if [ -z "$vm_args" ]; then
