Automated merge with file:///import/javaguest/ews/mjj/guestvm-devel-newmaxine/maxine

diff --git a/bin/max b/bin/max
--- a/bin/max
+++ b/bin/max
@@ -59,7 +59,7 @@
 verbose=false
 unknown_option=""
 show_help=false
-default_jvm_args="-d64 -ea -Xss2m -Xms1g -Xmx1g"
+default_jvm_args="-d64 -ea -Xss2m -Xmx1g"
 jvm_args="$default_jvm_args"
 jvm_args_prefix=""
 jvm_args_suffix=""
@@ -483,6 +483,30 @@ function run_clean() {
 
 
 #=======================================
+# 'jtt' command
+#=======================================
+
+jtt_usage="[JTMaxine args...]"
+jtt_help="run the JTMaxine program in the Maxine VM
+
+    Run the JTMaxine program in the Maxine VM with the given arguments.
+    The MAXVM_OPTIONS environment variable can be used to specify VM options.
+    
+    Use \"max vm -help\" to see what VM options are available.
+    Use \"max jtt -help\" to see what arguments the JTMaxine program accepts."
+
+function run_jtt() {
+    jtt_cp=$(get_project_cp VM)
+    jtt_cp=$jtt_cp:$(get_project_cp Base)
+    jtt_cp=$jtt_cp:$(get_project_cp CRI)
+    jtt_cp=$jtt_cp:$(get_project_cp C0X)
+    jtt_cp=$jtt_cp:$(get_project_cp C1X)
+    jtt_cp=$jtt_cp:$(get_project_cp Assembler)
+    jtt_cp=$jtt_cp:$JUNIT4_CP
+    run ${maxine_vm} -cp $jtt_cp $MAXVM_OPTIONS test.com.sun.max.vm.jtrun.JTMaxine -native-tests $@
+}
+
+#=======================================
 # 'jttgen' command
 #=======================================
 
@@ -726,12 +750,14 @@ function run_javadoc() {
 #=======================================
 
 image_configs=( \
-    java:-run=java \
-    c1x:-native-tests,-test-callee-c1x,-run=test.com.sun.max.vm.jtrun.c1x \
-    cpscps:-run=test.com.sun.max.vm.jtrun.all,-native-tests \
-    cpsjit:-run=test.com.sun.max.vm.jtrun.all,-native-tests,-test-callee-jit \
-    jitcps:-run=test.com.sun.max.vm.jtrun.all,-native-tests,-test-caller-jit \
-    jitjit:-run=test.com.sun.max.vm.jtrun.all,-native-tests,-test-caller-jit,-test-callee-jit \
+    java#-run=java \
+    c1x-opt0#-c1x-optlevel=0,-jit=com.sun.max.vm.compiler.c1x \
+    c1x-opt0-xir#-c1x-optlevel=0,-jit=com.sun.max.vm.compiler.c1x,--XX:+GenerateLIRXIR,--XX:+GenerateUnresolvedLIRXIR \
+    cpsc1x#-native-tests,-test-callee-c1x,-run=test.com.sun.max.vm.jtrun.all \
+    cpscps#-run=test.com.sun.max.vm.jtrun.all,-native-tests \
+    cpsjit#-run=test.com.sun.max.vm.jtrun.all,-native-tests,-test-callee-jit \
+    jitcps#-run=test.com.sun.max.vm.jtrun.all,-native-tests,-test-caller-jit \
+    jitjit#-run=test.com.sun.max.vm.jtrun.all,-native-tests,-test-caller-jit,-test-callee-jit \
 )
 
 image_usage="[options]"
@@ -744,17 +770,18 @@ image_help="build a boot image
 "
     
 image_help=$(printf "%s\n    %-15s %s\n " "$image_help" "Configuration" "Expansion")
+
 for image_config in ${image_configs[@]}; do
-    image_config_args="${image_config/*:/}"
-    image_help=$(printf "%s\n    @%-15s %s" "$image_help" "${image_config/:*/}" "${image_config_args//,/ }")
+    image_config_args="${image_config/*\#/}"
+    image_help=$(printf "%s\n    @%-15s %s" "$image_help" "${image_config/\#*/}" "${image_config_args//,/ }")
 done
 
 image_help="$image_help
     
     An option starting with '--' is interpreted as a VM option of the same name
-    after the leading '-' is removed. Note that not all VM options have an
-    effect during image building. For example, to use the '-verbose:class' VM option
-    to trace class loading while image building, specify '--verbose:class'.
+    after the leading '-' is removed. For example, to use the '-verbose:class'
+    VM option to trace class loading while image building, specify '--verbose:class'.
+    Note that not all VM options have an effect during image building. 
     
     Use \"max image -help\" to see what other options this command accepts."
     
@@ -766,21 +793,22 @@ function run_image() {
         case $1 in
             @*)
                 image_config_arg=${1/@/}
-                image_config_found=false
                 for image_config in ${image_configs[@]}; do
-                    image_config_name=${image_config/:*/}
+                    image_config_name=${image_config/\#*/}
                     if [ "$image_config_name" = "$image_config_arg" ]; then
-                        image_config_args="${image_config/*:/}"
-                        image_args="$image_args ${image_config_args//,/ }"
-                        image_config_found=true
-                        break
+                        image_config_args="${image_config/*\#/}"
+
+                        # Prepand the expanded macro to the positional parameters
+                        shift
+                        set -- ${image_config_args//,/ } "$@"
+
+                        # Continue at the outer 'while' loop                         
+                        continue 2
                     fi
                 done
-                if ! $image_config_found ; then
-                    echo "Invalid image configuration: $1"
-                    run_help image
-                    exit 1
-                fi
+                echo "Invalid image configuration: $1"
+                run_help image
+                exit 1
                 ;;
             --* )
                 if [ -z "$vm_args" ]; then
@@ -888,11 +916,29 @@ vm_usage="[options] [class | -jar jarfile]  [args...]"
 vm_help="launch the Maxine VM
 
     Run the Maxine VM with the given options and arguments.
+    The expansion of the MAXVM_OPTIONS environment variable is inserted
+    before any other VM options specified on the command line.
     
     Use \"max vm -help\" to see what other options this command accepts."
 
 function run_vm() {
     run ${maxine_vm} $MAXVM_OPTIONS $@
+}
+
+#=======================================
+# 'eclipse' command
+#=======================================
+
+eclipse_usage="[options]"
+eclipse_help="launch Eclipse with the Maxine VM
+
+    Run Eclipse under Maxine VM with the given options supplied as
+    the value of the '-vmargs' Eclipse launcher option.
+    The expansion of the MAXVM_OPTIONS environment variable is inserted
+    before any other VM options specified on the command line."
+
+function run_eclipse() {
+    run eclipse -vm ${maxine_vm} -vmargs $MAXVM_OPTIONS $@
 }
 
 #=======================================
@@ -958,6 +1004,7 @@ function run_inspect() {
 
     vm_args=""
     inspector_args=""
+    inspector_cp="";
     while [ "$1" != "" ]; do
         case $1 in
             -XX:LogFile=*)
@@ -972,12 +1019,15 @@ function run_inspect() {
                 vm_args="$vm_args $1"
                 shift
                 vm_args="$vm_args $1"
-                inspector_args="$inspector_args -cp=$1"
+                inspector_cp="$inspector_cp:$1"
                 ;;
             -jar )
                 shift
                 vm_args="$vm_args -jar $1"
-                inspector_args="$inspector_args -cp=$1"
+                inspector_cp="$inspector_cp:$1"
+                ;;
+            --cp=* )
+                inspector_cp="$inspector_cp:${1/--cp=/}"
                 ;;
             --* )
                 inspector_args="$inspector_args ${1/-/}"
@@ -988,6 +1038,10 @@ function run_inspect() {
         esac
         shift
     done    
+
+	if [ -n "$inspector_cp" ]; then
+	    inspector_args="$inspector_args -cp=${inspector_cp/:/}"
+	fi
 
     if [ "$MAXINE_OS" = "darwin" ]; then
         run sudo -p \
